version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file: 
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web: 
    image: messaging-app
    build: .
    container_name: django_app
    restart: always
    env_file: 
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "while ! mysqladmin ping -h db --silent; do sleep 2; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  mysql_data:
    driver: local